services:
  - type: web
    name: blog-fun
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-fun-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
databases:
  - name: blog-fun-db
    plan: free